# Generated by Django 3.2.9 on 2021-11-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehber',
            name='isimsoyisim',
            field=models.CharField(max_length=50),
        ),
    ]
