# Generated by Django 3.2.9 on 2021-11-13 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0002_alter_rehber_isimsoyisim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rehber',
            name='isimsoyisim',
        ),
        migrations.AddField(
            model_name='rehber',
            name='dtarih',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rehber',
            name='isim',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rehber',
            name='soyisim',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
